runtime: python37

entrypoint: gunicorn -b :$PORT main:app

handlers:
- url: /static
  static_dir: static
- url: /favicon\.ico
  static_files: static/monopolyTactileOverlay2.ico
  upload: static/favicon\.ico
- url: /favicon\.ico
  static_files: static/cardBraille2.ico
  upload: static/favicon\.ico
- url: /css/
  static_dir: /css/
- url: /
  static_files: templates/index.html
  upload: templates/index.html
- url: /aboutAccessibility
  static_files: templates/aboutAccessibility.html
  upload: templates/aboutAccessibility.html
- url: /gameSpecs
  static_files: templates/gameSpecs.html
  upload: templates/gameSpecs.html
- url: /accessWays
  static_files: templates/accessWays.html
  upload: templates/accessWays.html
- url: /theChecklist
  static_files: templates/theChecklist.html
  upload: templates/theChecklist.html
- url: /theBoardBraille
  static_files: templates/theBoardBraille.html
  upload: templates/theBoardBraille.html
- url: /boardBrailleAnnotation
  static_files: templates/boardBrailleAnnotation.html
  upload: templates/boardBrailleAnnotation.html
- url: /theBoardTactile
  static_files: templates/theBoardTactile.html
  upload: templates/theBoardTactile.html
- url: /boardTactileAnnotation
  static_files: templates/boardTactileAnnotation.html
  upload: templates/boardTactileAnnotation.html
- url: /gamePieces
  static_files: templates/gamePieces.html
  upload: templates/gamePieces.html
- url: /diceSpinner
  static_files: templates/diceSpinner.html
  upload: templates/diceSpinner.html
- url: /theCards
  static_files: templates/theCards.html
  upload: templates/theCards.html
- url: /scanCards
  static_files: templates/scanCards.html
  upload: templates/scanCards.html
- url: /cardUpload
  static_files: templates/cardUpload.html
  upload: templates/cardUpload.html
- url: /printLabel
  static_files: templates/printLabel.html
  upload: templates/printLabel.html
- url: /gameInstructions
  static_files: templates/gameInstructions.html
  upload: templates/gameInstructions.html
- url: /gameInstructions
  static_files: templates/gameInstructions.html
  upload: templates/gameInstructions.html
- url: /accessKit
  static_files: templates/accessKit.html
  upload: templates/accessKit.html